services:
  - type: web
    name: app-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python create_superuser.py"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: "https://app-frontend-7nug.onrender.com"

  - type: web
    env: static
    name: app-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        value: "https://app-backend-3bsg.onrender.com/api"
